
builds:
  - binary: mediumautopost
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: ghs
    homepage: "https://github.com/flexwie/ghs"
    tap:
      owner: flexwie
      name: homebrew-flexwie
    commit_author:
      name: flexwie
      email: ghs@felixwie.com

checksum:
  name_template: 'checksums.txt'