name: vhs
on:
  push:
    paths:
      - assets/demo.tape

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
      - name: Generate the gif with vhs
        run: |
          sudo apt update
          sudo apt install -y ffmpeg ttyd

          go install github.com/charmbracelet/vhs@latest
          go install .

          vhs assets/demo.tape
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "docs: updated gif"
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: "assets/*.gif"
